captainVersion: 4
services:
    $$cap_appname-server:
        image: ghcr.io/windmill-labs/windmill:$$cap_app_version
        expose:
            - 8000
        environment:
            DATABASE_URL: postgres://$$cap_postgres_user:$$cap_postgres_pass@$$cap_db_srv/$$cap_postgres_db?sslmode=disable
            MODE: server
        # depends_on:
        #     - $$cap_db_srv
        caproverExtra:
            containerHttpPort: 8000

    $$cap_appname-worker:
        image: ghcr.io/windmill-labs/windmill:$$cap_app_version
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $$cap_appname-worker-dependency-cache:/tmp/windmill/cache
        environment:
            DATABASE_URL: postgres://$$cap_postgres_user:$$cap_postgres_pass@$$cap_db_srv/$$cap_postgres_db?sslmode=disable
            MODE: worker
            WORKER_GROUP: default
        # depends_on:
        #     - $$cap_db_srv
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-worker-native:
        image: ghcr.io/windmill-labs/windmill:$$cap_app_version
        environment:
            DATABASE_URL: postgres://$$cap_postgres_user:$$cap_postgres_pass@$$cap_db_srv/$$cap_postgres_db?sslmode=disable
            MODE: worker
            WORKER_GROUP: native
        # depends_on:
        #     - $$cap_db_srv
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-lsp:
        image: ghcr.io/windmill-labs/windmill-lsp:$$cap_app_version
        volumes:
            - $$cap_appname-lsp-cache:/root/.cache
        expose:
            - 3001
        caproverExtra:
            containerHttpPort: 3001
            notExposeAsWebApp: 'true'

caproverOneClickApp:
    instructions:
        start: |-
            Windmill is an open-source alternative to Retool, Airplane and n8n to build all your internal tools (endpoints, workflows, UIs) through simple scripts - in Typescript, Python, Go & Bash - and low code builders.
        end: |-
            Windmill has been successfully deployed!
            Please change the following settings before using the service:
            1. Go to the settings for `$$cap_appname`
            2. Enable **Websocket Support**
            3. Enable **HTTPS**
            4. Click on **Edit Default Nginx Configurations** and paste the following content before the last closing bracket "}":
                ```
                location /ws/ {
                    proxy_pass http://srv-captain--$$cap_appname-lsp:3001/ws/;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                }
                ```
            Now you can access it at `https://$$cap_appname.$$cap_root_domain`

            Default e-mail is `admin@windmill.dev` and the password is `changeme`

    displayName: Windmill
    isOfficial: true
    description: Windmill is an open-source alternative to Retool, Airplane and n8n.
    documentation: https://windmill.dev
    variables:
        - id: $$cap_app_version
          label: Windmill Version
          defaultValue: '1.228.0'
          description: Checkout their github page for the valid tags https://github.com/windmill-labs/windmill/releases
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_db
          label: Postgres Database Name
          defaultValue: 'windmill'
          description: Create A Database Before You Start.
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_user
          label: Potgress Database User
          description: 'User for postgres'
          defaultValue: 'windmill'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_pass
          label: Potgress Database password
          description: 'Password for postgres'
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /^([^\s^\/])+$/
        
        - id: $$cap_db_srv
          label: Inner PostgreSQL Service Name(srv-captain--postgres)
          defaultValue: 'srv-captain--postgres'